### ISSUE TITLE
Point zxing-typescript as a dependency

### ISSUE THREAD

**Issue by odahcam** [werthdavid/ngx-zxing#2]
[zxing-typescript](https://github.com/aleris/zxing-typescript) should be imported inside this versioned code, it should be used as a dependency instead.

**Comment by werthdavid** [comment]
I actually tried that in the first place but can't import zxing-typescript with .forRoot() or anything since it is not a proper lib/module.
It's my first angular library, feel free to make a PR :-)

**Comment by odahcam** [comment]
All right, I will try then. 🙂

**Comment by odahcam** [comment]
Well, I managed to build the project with zxing-ts as a dependency. I also updated the code to Angular 5 patterns. 🎉

**Comment by werthdavid** [comment]
Okay so what are we gonna do?

**Comment by odahcam** [comment]
I'm trying to fix zxing-typescript package right now. 😅

**Comment by werthdavid** [comment]
Cool, what can I do? Will probably have some time during the holidays

**Comment by odahcam** [comment]
Nice, I've successful installed the package dependencies only today, 'cause I had a problem with one of them (`sharp` who has some peculiar dependencies).

Also, I can already create a bundle of the project, but I need to test if it will work with `ngx-zxing`. 

If you want to make any improvements in the code or help with tests or getting `ngx-zxing` to work with the package would me awesome. Basically I don't know what you can do, but I would appreciate.

When we finish we can ~try~ to merge my fork back here.

**Comment by odahcam** [comment]
I've done. I fixed `zxing-typescript` build in my fork and published it, now `ngx-zxing` is using the fixed version instead of the original.

**Comment by werthdavid** [comment]
Awesome!! You wanna make a PR to merge your changes back here? What about zxing-ts, are you maintaining the fork or will aleris accept a PR?

**Comment by odahcam** [comment]
Well, lets try to merge ngx-zxing back here! About zxing-ts, I don't think @aleris will accept that quantity of changes in a single take, so I will keep the fork for a while until we decide what happens to it.

I just think that my ngx-zxing fork is not ready for a PR, there's still things I have to fix. I've done the dependency task, but I changed the project structure and messed up with the component, I pretend to fix it up today and then make the PR.

**Comment by aleris** [comment]
I would greatly appreciate a PR, would be great if would be focused and manageable to merge. Thanks!

**Comment by odahcam** [comment]
Can you take a look in my fork and give some feedback to us? :)

**Comment by odahcam** [comment]
I made progress with both packages. We can start thinking in the future of both and if the PRs are gonna happen.

Here is an example of everything (I bet/hope) working: https://stackblitz.com/edit/ngx-zxing-2-exemple

**Comment by werthdavid** [comment]
Changes of ngx-zxing look fine for me.

**Comment by werthdavid** [comment]
@odahcam Whats your idea for the project? Do you want to push the changes you made back here or are you gonna maintain your fork?

**Comment by odahcam** [comment]
Well, at this time I need to be able to publish versions everytime I need them, I can't be forced to wait cause I need some features for like yesterday. 😆 

If I my need can be satisfied here, I can make a PR today, if it does not I will have to wait a little more to PR my changes back.

**Comment by werthdavid** [comment]
Sure thing, not a problem, just wanted to know :wink:
I just had the feeling that some to the issues that arouse here, could potentially already be fixed in your code base.

By the way, thanks for the great work, I really appreciate it!

**Comment by odahcam** [comment]
You're welcome! Sure something I got fixed, but that issues I created today are still a problem in my branch that I'll try to fix week. Also I'm planing to create another demo with angular/material and more user interactions.

**Comment by odahcam** [comment]
@werthdavid what you think about publishing the package under a npm-scope?

**Comment by werthdavid** [comment]
sure, what did you think of?

**Comment by odahcam** [comment]
About the scope name or the idea? 

Scope could be `@zxing/ngx-scanner` or anything else, I really did not think about what could be a good name, so much so that I put a random name (`@barn/ngx-zxing`) in my published package just to have it published.

About the idea it is cool because the scope owner can manage who can publish in that package, so you could set publish permissions for both of us. That would make things easier and bring more flexibility for me.

**Comment by werthdavid** [comment]
Both sounds good 😉

**Comment by odahcam** [comment]
I created *zxing* org. on NPM (I can't believe it was not created yet), so tell me if you wanna to go ahead with this and lets see what we can do. 😀

**Comment by werthdavid** [comment]
I'm good 2 go, lets do it!

**Comment by odahcam** [comment]
Nice! So now we need to start to deprecate our own packages and point to the zxing scope publish and, obviously, publish something under the scope too, hehe. I can do something with my repo tonight and also finish the PR #20 .
